# Generated by Django 5.2.7 on 2026-08-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Newsletter subscriber',
                'verbose_name_plural': 'Newsletter subscribers',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone number')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject')),
                ('content', models.TextField(max_length=700, verbose_name='Message content')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Seen by admin')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Contact ticket',
                'verbose_name_plural': 'Contact tickets',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['is_seen'], name='website_con_is_seen_b2283d_idx'), models.Index(fields=['created_date'], name='website_con_created_b89f7d_idx')],
            },
        ),
    ]
