# Generated by Django 5.2.7 on 2026-01-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=4)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login')], db_index=True, default='signup', max_length=20)),
                ('is_consumed', models.BooleanField(default=False)),
                ('expire_at', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('consumed_date', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['email', 'purpose', 'is_consumed'], name='accounts_em_email_0ab305_idx')],
            },
        ),
    ]
