# Generated by Django 5.2.7 on 2026-06-26 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_devicesession_revoked_at_refreshtoken_family_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('otp_requested', 'OTP Requested'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('login', 'Login'), ('logout', 'Logout')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'created_at'], name='accounts_au_action_6cf40e_idx'), models.Index(fields=['ip_address'], name='accounts_au_ip_addr_fe91c7_idx')],
            },
        ),
    ]
