# Generated by Django 5.2.7 on 2026-02-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditevent_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='code_hash',
            field=models.CharField(max_length=125),
        ),
    ]
