# Generated by Django 5.2.7 on 2026-08-21 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Globally unique idempotency key for this event.', unique=True)),
                ('topic', models.CharField(db_index=True, help_text='Routing key for dispatchers (e.g. user.otp)', max_length=100)),
                ('payload', models.JSONField(help_text='Event data payload (must be serializable & validated)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_date'],
                'indexes': [models.Index(fields=['status', 'retry_count'], name='events_outb_status_e17a58_idx'), models.Index(fields=['status', 'created_date'], name='events_outb_status_01c531_idx'), models.Index(fields=['topic', 'status'], name='events_outb_topic_134189_idx')],
            },
        ),
    ]
