[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_tests.py
; addopts = -p no:warnings
env =
    TESTING=1

addopts =
    -ra
    --strict-markers
    --reuse-db
    --tb=short

markers =
    unit
    service
    integration
    performance
    concurrency
    e2e
    slow
