# Generated by Django 5.2.7 on 2026-06-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Show'), (2, "Don't show")], default=2),
        ),
    ]
