# Generated by Django 5.2.7 on 2026-08-21 02:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_limit_usage', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='coupon_discount_percent_valid'), models.CheckConstraint(condition=models.Q(('max_limit_usage__gte', 0)), name='coupon_max_usage_non_negative'), models.CheckConstraint(condition=models.Q(('used_count__gte', 0)), name='coupon_used_count_non_negative'), models.CheckConstraint(condition=models.Q(('used_count__lte', models.F('max_limit_usage'))), name='coupon_used_count_lte_max_usage')],
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('ONLINE', 'Online')], default='ONLINE', max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Pending Payment'), (2, 'Payment Failed'), (3, 'Paid'), (4, 'Processing'), (5, 'Shipped'), (6, 'Delivered'), (7, 'Return Requested'), (8, 'Returned'), (9, 'Refunded'), (10, 'Cancelled')], db_index=True, default=1)),
                ('total_price', models.DecimalField(decimal_places=0, help_text='Legacy gross order total.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('subtotal_price', models.DecimalField(decimal_places=0, default=0, help_text='Total price of order items before discount.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, help_text='Total discount applied to the order.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_price', models.DecimalField(decimal_places=0, default=0, help_text='Shipping cost snapshot.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, help_text='Tax amount snapshot.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payable_price', models.DecimalField(decimal_places=0, default=0, help_text='Final amount that customer must pay.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(db_index=True, help_text='Order expiration time for unpaid orders')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.couponmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.ordermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Order Created'), ('PAYMENT_STARTED', 'Payment Started'), ('PAID', 'Payment Successful'), ('PROCESSING', 'Order Processing'), ('SHIPPED', 'Order Shipped'), ('DELIVERED', 'Order Delivered'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('EXPIRED', 'Order Expired'), ('CANCELLED', 'Order Cancelled'), ('REFUNDED', 'Order Refunded'), ('ADMIN_NOTE', 'Admin Note')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='order.ordermodel')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='UserAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['status', 'expire_at'], name='order_order_status_8b3d75_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['user', '-created_date'], name='order_order_user_id_e9a85a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['paid_date'], name='order_order_paid_da_f28996_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['completed_date'], name='order_order_complet_5d4cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['cancelled_date'], name='order_order_cancell_24e627_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordermodel',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('subtotal_price'))), name='discount_less_than_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='ordermodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_date__isnull', True), models.Q(('status__in', [3, 4, 5, 6, 7, 8, 9]), _negated=True)), ('paid_date__isnull', False), _connector='OR'), name='order_paid_date_consistent'),
        ),
    ]
