# Generated by Django 5.2.7 on 2025-12-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_couponmodel_options_remove_couponmodel_used_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'موفق'), (3, 'ناموفق'), (4, 'لغو شده'), (5, 'مرجوع شده')], default=1),
        ),
    ]
