# Generated by Django 5.2.7 on 2026-01-02 17:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='expire_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 1, 2, 17, 12, 30, 492030, tzinfo=datetime.timezone.utc), help_text='Order expiration time for unpaid orders'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Order Created'), ('PAYMENT_STARTED', 'Payment Started'), ('PAID', 'Payment Successful'), ('EXPIRED', 'Order Expired'), ('CANCELLED', 'Order Cancelled'), ('REFUNDED', 'Order Refunded'), ('ADMIN_NOTE', 'Admin Note')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='order.ordermodel')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
