# Generated by Django 5.2.7 on 2026-01-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_ordermodel_payment_ordermodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'موفق'), (3, 'ناموفق'), (4, 'لغو شده'), (5, 'مرجوع شده')], db_index=True, default=1),
        ),
    ]
