# Generated by Django 5.2.7 on 2026-06-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('CREATED', 'Order Created'), ('PAYMENT_STARTED', 'Payment Started'), ('PAID', 'Payment Successful'), ('PROCESSING', 'Order Processing'), ('SHIPPED', 'Order Shipped'), ('DELIVERED', 'Order Delivered'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('EXPIRED', 'Order Expired'), ('CANCELLED', 'Order Cancelled'), ('REFUNDED', 'Order Refunded'), ('ADMIN_NOTE', 'Admin Note')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='sale_type',
            field=models.CharField(choices=[('ONLINE', 'Online')], default='ONLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending Payment'), (2, 'Payment Failed'), (3, 'Paid'), (4, 'Processing'), (5, 'Shipped'), (6, 'Delivered'), (7, 'Return Requested'), (8, 'Returned'), (9, 'Refunded'), (10, 'Cancelled')], db_index=True, default=1),
        ),
    ]
