# core/payment/services/factory.py

from __future__ import annotations

from decimal import Decimal
from typing import Any

from django.conf import settings
from django.core.exceptions import ValidationError

from payment.enums import Currency, PaymentGateway, PaymentStatusType
from payment.models import PaymentModel


class PaymentFactory:
    """
    Factory for creating a Payment aggregate.

    Payment owns only financial and aggregate-level state.

    Gateway execution identity such as:

        authority_id
        gateway_reference
        gateway_transaction_id
        ref_id

    belongs exclusively to PaymentAttempt and must never be accepted
    or generated by this factory.

    Gateway HTTP, transactions, locking, repositories and workflow
    orchestration are outside this factory.
    """

    @staticmethod
    def create(
        *,
        order: Any,
        amount: Decimal,
        currency: Currency | str | None = None,
        gateway: PaymentGateway | str | None = None,
        status: PaymentStatusType = PaymentStatusType.PENDING,
    ) -> PaymentModel:
        """
        Create a Payment aggregate.

        This method only constructs and persists Payment-owned state.

        It does not:

        - call a gateway
        - generate gateway identity
        - create PaymentAttempt
        - open a transaction
        - lock database rows
        - mutate Order
        - publish events
        """

        if order is None or getattr(order, "pk", None) is None:
            raise ValidationError(
                "A persisted order is required to create a payment."
            )

        normalized_amount = Decimal(str(amount))

        if normalized_amount <= Decimal("0"):
            raise ValidationError(
                "Payment amount must be greater than zero."
            )

        normalized_currency = (
            str(
                currency
                or getattr(
                    settings,
                    "DEFAULT_CURRENCY",
                    Currency.IRR,
                ),
            )
            .strip()
            .upper()
        )

        if not normalized_currency:
            raise ValidationError(
                "Payment currency is required."
            )

        normalized_gateway = (
            gateway
            or getattr(
                settings,
                "DEFAULT_PAYMENT_GATEWAY",
                None,
            )
        )

        if normalized_gateway is None:
            raise ValidationError(
                "Payment gateway is required."
            )

        if isinstance(normalized_gateway, PaymentGateway):
            gateway_value = normalized_gateway.value
        else:
            gateway_value = str(normalized_gateway).strip()

        if not gateway_value:
            raise ValidationError(
                "Payment gateway is required."
            )

        return PaymentModel.objects.create(
            order=order,
            amount=normalized_amount,
            currency=normalized_currency,
            gateway=gateway_value,
            status=status,
        )
        
        
        # PaymentFactory
        #     ↓
        # Payment
        #     ↓
        # PaymentAttempt
        #     ↓
        # COMMIT
        #     ↓
        # Gateway Adapter