# Generated by Django 5.2.7 on 2026-08-21 02:20

import django.core.serializers.json
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Immutable financial amount of this payment.', max_digits=12)),
                ('currency', models.CharField(choices=[('IRR', 'IRR')], default='IRR', help_text='Immutable currency of this payment.', max_length=8)),
                ('gateway', models.CharField(choices=[('zarinpal', 'Zarinpal'), ('stripe', 'Stripe'), ('paypal', 'Paypal'), ('mellat', 'Mellat'), ('unknown', 'Unknown')], db_index=True, max_length=32)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Successful'), (3, 'Failed')], db_index=True, default=1)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency version. The repository owns CAS persistence.')),
                ('is_consumed', models.BooleanField(default=False)),
                ('is_refunded', models.BooleanField(default=False, help_text='True only when the Payment has been fully refunded.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.ordermodel')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ('-created_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(help_text='Monotonically increasing attempt number within the payment.')),
                ('authority_id', models.CharField(blank=True, db_index=True, default='', help_text='Gateway authority/token assigned to this attempt.', max_length=128)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, default='', help_text='Gateway reference assigned after successful execution.', max_length=128)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, default='', help_text='Gateway-side transaction identifier.', max_length=128)),
                ('retry_count', models.PositiveSmallIntegerField(default=1, help_text='Retry sequence number represented by this attempt.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current lifecycle state of this payment attempt.', max_length=20)),
                ('response_code', models.CharField(blank=True, default='', help_text='Normalized gateway response code.', max_length=64)),
                ('gateway_message', models.CharField(blank=True, default='', help_text='Normalized gateway response message.', max_length=255)),
                ('failure_reason', models.CharField(blank=True, default='', help_text='Internal normalized reason for technical/business failure.', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp at which this attempt execution started.')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Timestamp at which this attempt reached a terminal state.', null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='Measured execution latency in milliseconds.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address associated with this attempt.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Client user-agent associated with this attempt.')),
                ('meta', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Non-sensitive structured metadata associated with this attempt.')),
                ('retry_of', models.ForeignKey(blank=True, help_text='Historical attempt from which this retry originated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='payment.paymentattempt')),
                ('payment', models.ForeignKey(help_text='Payment aggregate that owns this attempt.', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payment.paymentmodel')),
            ],
            options={
                'verbose_name': 'Payment Attempt',
                'verbose_name_plural': 'Payment Attempts',
                'ordering': ('-attempt_number', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Immutable refund amount in the Payment currency.', max_digits=12)),
                ('currency', models.CharField(choices=[('IRR', 'IRR')], default='IRR', help_text='Immutable currency snapshot of the Payment.', max_length=8)),
                ('idempotency_key', models.CharField(help_text='Stable idempotency identity for this refund request.', max_length=128, unique=True)),
                ('reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('admin', 'Admin'), ('fraud', 'Fraud'), ('duplicate', 'Duplicate Payment'), ('failed_delivery', 'Failed Delivery'), ('other', 'Other')], default='other', max_length=32)),
                ('reason_detail', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, default='', help_text='Gateway-specific refund reference or authority.', max_length=128)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, default='', help_text='Gateway-specific refund transaction identifier.', max_length=128)),
                ('response_code', models.CharField(blank=True, default='', help_text='Normalized gateway response code.', max_length=64)),
                ('gateway_message', models.CharField(blank=True, default='', help_text='Normalized gateway response message.', max_length=255)),
                ('failure_reason', models.CharField(blank=True, default='', help_text='Normalized refund failure reason.', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('payment', models.ForeignKey(help_text='Payment aggregate to which this refund belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payment.paymentmodel')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ('-requested_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='GatewayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zarinpal', 'Zarinpal'), ('stripe', 'Stripe'), ('paypal', 'Paypal'), ('mellat', 'Mellat'), ('unknown', 'Unknown')], db_index=True, help_text='Payment gateway involved in this communication.', max_length=32)),
                ('log_type', models.CharField(choices=[('request', 'Request'), ('response', 'Response'), ('callback', 'Callback'), ('verify', 'Verify'), ('refund', 'Refund'), ('webhook', 'Webhook'), ('error', 'Error')], db_index=True, help_text='Type of gateway communication.', max_length=32)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], db_index=True, help_text='Direction of communication between application and gateway.', max_length=16)),
                ('request_url', models.URLField(blank=True, default='', help_text='Gateway endpoint URL used for this request.', max_length=2048)),
                ('request_method', models.CharField(blank=True, default='', help_text='HTTP method used for the request.', max_length=16)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, help_text='HTTP status code returned by the gateway.', null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='Measured request latency in milliseconds.', null=True)),
                ('request_headers', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Sanitized HTTP request headers sent to the gateway.')),
                ('request_payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Sanitized request payload sent to the gateway.')),
                ('response_headers', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Sanitized HTTP response headers returned by the gateway.')),
                ('response_payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Sanitized response payload returned by the gateway.')),
                ('response_code', models.CharField(blank=True, db_index=True, default='', help_text='Normalized gateway response code.', max_length=64)),
                ('gateway_message', models.CharField(blank=True, default='', help_text='Normalized gateway response message.', max_length=255)),
                ('is_success', models.BooleanField(blank=True, db_index=True, help_text='Normalized gateway communication result.', null=True)),
                ('exception', models.TextField(blank=True, default='', help_text='Captured technical exception information.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address associated with this gateway communication.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Client user-agent associated with this gateway communication.')),
                ('meta', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Additional non-sensitive structured audit metadata.')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this audit record was created.')),
                ('attempt', models.ForeignKey(blank=True, help_text='Payment attempt associated with this gateway communication.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gateway_logs', to='payment.paymentattempt')),
                ('refund', models.ForeignKey(blank=True, help_text='Refund associated with this gateway communication.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gateway_logs', to='payment.refund')),
            ],
            options={
                'verbose_name': 'Gateway Log',
                'verbose_name_plural': 'Gateway Logs',
                'ordering': ('-created_date', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['gateway', 'status'], name='payment_gateway_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['order', 'status'], name='payment_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['created_date'], name='payment_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='payment_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('currency__gt', '')), name='payment_currency_required'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('order',), name='payment_one_pending_per_order'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['payment', 'status', '-attempt_number'], name='pay_attempt_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['status', '-started_at'], name='pay_attempt_status_started_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['payment', 'gateway_reference'], name='pay_attempt_payment_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['payment', 'gateway_transaction_id'], name='pay_attempt_payment_tx_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['payment', 'authority_id'], name='pay_attempt_payment_auth_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['retry_of'], name='pay_attempt_retry_of_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('payment', 'attempt_number'), name='payment_attempt_payment_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='payment_attempt_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__gte', 1)), name='payment_attempt_retry_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'success'), _negated=True), ('gateway_reference__gt', ''), _connector='OR'), name='payment_attempt_success_requires_ref'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'success'), _negated=True), ('authority_id__gt', ''), _connector='OR'), name='payment_attempt_success_requires_authority'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'pending')), models.Q(('finished_at__isnull', False), ('status__in', ['success', 'failed', 'timeout', 'cancelled'])), _connector='OR'), name='payment_attempt_finished_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='payment_attempt_finish_after_start'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status', '-requested_at'], name='refund_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', '-requested_at'], name='refund_status_requested_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', '-requested_at'], name='refund_payment_requested_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('currency__gt', '')), name='refund_currency_required'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'IRR')), name='refund_v1_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key__gt', '')), name='refund_idempotency_key_required'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'pending')), models.Q(('finished_at__isnull', False), ('status__in', ('success', 'failed'))), _connector='OR'), name='refund_finished_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('requested_at')), _connector='OR'), name='refund_finish_after_request'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'success'), _negated=True), ('gateway_reference__gt', ''), ('gateway_transaction_id__gt', ''), _connector='OR'), name='refund_success_requires_gateway_identity'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'success'), _negated=True), ('failure_reason', ''), _connector='OR'), name='refund_success_no_failure_reason'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'failed'), _negated=True), ('failure_reason__gt', ''), _connector='OR'), name='refund_failed_requires_failure_reason'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_reference__gt', '')), fields=('payment', 'gateway_reference'), name='refund_payment_gateway_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_transaction_id__gt', '')), fields=('payment', 'gateway_transaction_id'), name='refund_payment_gateway_tx_uniq'),
        ),
        migrations.AddIndex(
            model_name='gatewaylog',
            index=models.Index(fields=['attempt', '-created_date'], name='gw_log_attempt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaylog',
            index=models.Index(fields=['refund', '-created_date'], name='gw_log_refund_created_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaylog',
            index=models.Index(fields=['gateway', 'log_type', '-created_date'], name='gw_log_gateway_type_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaylog',
            index=models.Index(fields=['gateway', 'is_success', '-created_date'], name='gw_log_gateway_success_idx'),
        ),
        migrations.AddConstraint(
            model_name='gatewaylog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attempt__isnull', False), ('refund__isnull', True)), models.Q(('attempt__isnull', True), ('refund__isnull', False)), _connector='OR'), name='gateway_log_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='gatewaylog',
            constraint=models.CheckConstraint(condition=models.Q(('http_status__isnull', True), models.Q(('http_status__gte', 100), ('http_status__lte', 599)), _connector='OR'), name='gateway_log_http_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='gatewaylog',
            constraint=models.CheckConstraint(condition=models.Q(('latency_ms__isnull', True), ('latency_ms__gte', 0), _connector='OR'), name='gateway_log_latency_non_negative'),
        ),
    ]
