# Generated by Django 5.2.7 on 2026-01-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_ordermodel_payment_ordermodel_expire_at_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='gateway',
            field=models.CharField(default='ZARINPAL', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='is_consumed',
            field=models.BooleanField(default=False, help_text='Used to finalize order (idempotency guard)'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.ordermodel'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='authority_id',
            field=models.CharField(help_text='Gateway authority / token', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='response_json',
            field=models.JSONField(default=dict, help_text='Raw gateway response'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['authority_id'], name='payment_pay_authori_b69dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['status'], name='payment_pay_status_46b312_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['order', 'status'], name='payment_pay_order_i_dd923f_idx'),
        ),
    ]
