# Generated by Django 5.2.7 on 2026-06-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentmodel_options_paymentmodel_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Successful'), (3, 'Failed')], default=1),
        ),
    ]
