# Generated by Django 5.2.7 on 2026-07-22 04:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderevent_type_alter_ordermodel_sale_type_and_more'),
        ('payment', '0003_alter_paymentmodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentmodel',
            name='payment_pay_authori_b69dfd_idx',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='response_json',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Irr'), ('IRT', 'Irt'), ('USD', 'Usd')], default='IRR', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='gateway_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='is_refunded',
            field=models.BooleanField(db_index=True, default=False, help_text='Gateway refund completed.'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='merchant_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='net_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='provider_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='refund_ref_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='refund_request',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='refund_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='authority_id',
            field=models.CharField(editable=False, help_text='Gateway authority / token', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='gateway',
            field=models.CharField(choices=[('zarinpal', 'Zarinpal'), ('stripe', 'Stripe'), ('paypal', 'Paypal'), ('mellat', 'Mellat'), ('unknown', 'Unknown')], db_index=True, default='zarinpal', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='ref_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['gateway', 'status'], name='payment_pay_gateway_cb49f7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['created_date'], name='payment_pay_created_1a9a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['order', 'created_date'], name='payment_pay_order_i_776622_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['order', 'status', '-created_date'], name='payment_pay_order_i_446535_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('is_consumed', False), ('status', 2), _connector='OR'), name='consumed_requires_success'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('is_refunded', False), ('refund_date__isnull', False), _connector='OR'), name='refund_date_exists'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('verified_date__isnull', True), ('status', 2), _connector='OR'), name='verified_requires_success'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('ref_id__isnull', True), ('status', 2), _connector='OR'), name='reference_requires_success'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('refund_ref_id__isnull', True), ('is_refunded', True), _connector='OR'), name='refund_reference_requires_refund'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('paid_date__isnull', True), ('status', 2), _connector='OR'), name='paid_date_requires_success'),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('gateway_transaction_id', ''), ('status', 2), _connector='OR'), name='gateway_transaction_requires_success'),
        ),
    ]
