# Generated by Django 5.2.7 on 2026-07-22 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderevent_type_alter_ordermodel_sale_type_and_more'),
        ('payment', '0004_remove_paymentmodel_payment_pay_authori_b69dfd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('refund_date__isnull', True), ('is_refunded', True), _connector='OR'), name='refund_flag_required'),
        ),
    ]
